hmrc/tai

- app/uk/gov/hmrc/tai/controllers/EmploymentsController.scala
- test/uk/gov/hmrc/tai/controllers/EmploymentsControllerSpec.scala
Exposing BadRequestException in Employments API.
> TAI-3777 : Remove SessionData dependency from WDYWTD page

- conf/application.conf
> ST-115: Toggle tax code change on

- conf/application.conf
> Add flag to redeploy with new commit hash

- README.md
- docs/taxaccount/tax-code-change-exists.md
- docs/taxaccount/tax-code-change.md
- Change to endpoint url
- Additional fields in JSON response for a tax code change item
Check
> ST-154: Update API documentation for tax code change.

- app/uk/gov/hmrc/tai/model/domain/Employment.scala
- app/uk/gov/hmrc/tai/model/domain/formatters/EmploymentHodFormatters.scala
- test/uk/gov/hmrc/tai/controllers/EmploymentsControllerSpec.scala
- test/uk/gov/hmrc/tai/model/domain/EmploymentSpec.scala
- test/uk/gov/hmrc/tai/model/domain/formatters/EmploymentHodFormattersSpec.scala
- test/uk/gov/hmrc/tai/model/domain/formatters/EmploymentMongoFormattersSpec.scala
- test/uk/gov/hmrc/tai/model/templates/EmploymentPensionViewModelSpec.scala
- test/uk/gov/hmrc/tai/repositories/EmploymentRepositorySpec.scala
- test/uk/gov/hmrc/tai/service/EmploymentServiceSpec.scala
- test/uk/gov/hmrc/tai/service/IncomeServiceSpec.scala
- test/uk/gov/hmrc/tai/service/PensionProviderServiceSpec.scala
> ST-175: Add receivingOccupationalPension to Employment Model

- docs/taxaccount/tax-code-change.md
- Tax code change returns an array of tax code items.
> Update tax code change endpoint.

- app/uk/gov/hmrc/tai/controllers/CodingComponentController.scala
- test/uk/gov/hmrc/tai/controllers/CodingComponentControllerSpec.scala
> DDCNOS-52: stopped exception being thrown for Bad Requests

- project/Microservice.scala
- project/plugins.sbt
> updating config for new build

- app/uk/gov/hmrc/tai/controllers/taxCodeChange/TaxCodeChangeController.scala
- conf/application.conf
> ST-323: Add logging for tax code change

- app/uk/gov/hmrc/tai/controllers/taxCodeChange/TaxCodeChangeController.scala
> ST-323: Change logger library

- app/uk/gov/hmrc/tai/controllers/taxCodeChange/TaxCodeChangeController.scala
- app/uk/gov/hmrc/tai/service/TaxCodeChangeService.scala
> Add additional TaxCodeChange logging

- conf/application.conf
data will now be passed by DES, needs extensive testing
> DDCNLS-4734 | toggled des configuration to TRUE

- conf/application.conf
> Ddcnls-4734: reset config to false

- app/uk/gov/hmrc/tai/connectors/ApplicationUrls.scala
- test/uk/gov/hmrc/tai/connectors/ApplicationUrlsSpec.scala
- test/uk/gov/hmrc/tai/connectors/TaxAccountConnectorSpec.scala
changed URL accordingly to the ticket and unit tests
> DDCNLS-4733

- app/uk/gov/hmrc/tai/connectors/ApplicationUrls.scala
- test/uk/gov/hmrc/tai/connectors/ApplicationUrlsSpec.scala
- test/uk/gov/hmrc/tai/connectors/TaxAccountConnectorSpec.scala
restored calculation to hypothetical, restored unit test
> DDCNLS-4733 restore calculation to hypothetical

- app/uk/gov/hmrc/tai/service/TaxCodeChangeService.scala
- test/uk/gov/hmrc/tai/service/TaxCodeChangeServiceImplSpec.scala
> ST-361: Only show mismatch is there has been a tax code change

- conf/application.conf
- test/uk/gov/hmrc/tai/controllers/taxCodeChange/TaxCodeChangeControllerSpec.scala
> ST-361: toggle tax code change on

- app/uk/gov/hmrc/tai/service/TaxCodeChangeService.scala
http://localhost:9332/individuals/tax-code-history/list/AN986715A/2018?endTaxYear=2019
> ST-379: Correct end year for tax code history

- app/uk/gov/hmrc/tai/controllers/income/IncomeController.scala
- app/uk/gov/hmrc/tai/service/IncomeService.scala
- test/uk/gov/hmrc/tai/service/IncomeServiceSpec.scala
When update is for next year, do a single update for next year.
> ST-397: Update for next year income estimate

- app/uk/gov/hmrc/tai/connectors/ApplicationUrls.scala
- test/uk/gov/hmrc/tai/connectors/ApplicationUrlsSpec.scala
- test/uk/gov/hmrc/tai/connectors/TaxAccountConnectorSpec.scala
> API Reverted back to Calculation API

- test/uk/gov/hmrc/tai/connectors/TaxCodeChangeConnectorSpec.scala
- test/uk/gov/hmrc/tai/factory/TaxCodeHistoryFactory.scala
- test/uk/gov/hmrc/tai/factory/TaxCodeRecordFactory.scala
- test/uk/gov/hmrc/tai/model/TaxCodeHistorySpec.scala
- test/uk/gov/hmrc/tai/service/TaxCodeChangeServiceImplSpec.scala
> Convert TaxCodeRecord, TaxCodeHistory to Spec Factory

- app/uk/gov/hmrc/tai/connectors/DesConnector.scala
- app/uk/gov/hmrc/tai/controllers/expenses/FlatRateExpensesController.scala
- app/uk/gov/hmrc/tai/model/IabdUpdateExpensesAmount.scala
- app/uk/gov/hmrc/tai/model/IabdUpdateExpensesData.scala
- app/uk/gov/hmrc/tai/model/UpdateIabdDataModel.scala
- app/uk/gov/hmrc/tai/service/expenses/FlatRateExpensesService.scala
- conf/app.routes
- test/uk/gov/hmrc/tai/connectors/DesConnectorSpec.scala
- test/uk/gov/hmrc/tai/controllers/expenses/FlatRateExpensesControllerSpec.scala
- test/uk/gov/hmrc/tai/model/IabdUpdateExpensesAmountSpec.scala
- test/uk/gov/hmrc/tai/model/IabdUpdateExpensesDataSpec.scala
- test/uk/gov/hmrc/tai/service/expenses/FlatRateExpensesServiceSpec.scala
> EE-43 update flat rate expenses endpoint

- app/uk/gov/hmrc/tai/service/TaxCodeChangeService.scala
- test/uk/gov/hmrc/tai/service/TaxCodeChangeServiceImplSpec.scala
> ST-421: adding logging for taxCodeRecords outside of given tax year

- app/uk/gov/hmrc/tai/service/TaxCodeChangeService.scala
> ST-421:Change logging level

- app/uk/gov/hmrc/tai/service/TaxCodeChangeService.scala
> ST-421: Change log message

- app/uk/gov/hmrc/tai/service/TaxCodeChangeService.scala
- test/uk/gov/hmrc/tai/service/TaxCodeChangeServiceImplSpec.scala
> Updating end tax year to be same as start

- app/uk/gov/hmrc/tai/service/IncomeService.scala
- test/uk/gov/hmrc/tai/service/IncomeServiceSpec.scala
> Fix root version for CY+1 Update

- app/uk/gov/hmrc/tai/service/IncomeService.scala
- test/uk/gov/hmrc/tai/service/IncomeServiceSpec.scala
> Update Estimated pay only for year passed

- app/uk/gov/hmrc/tai/controllers/income/IncomeController.scala
- app/uk/gov/hmrc/tai/service/IncomeService.scala
- test/uk/gov/hmrc/tai/service/IncomeServiceSpec.scala
> ST-422 Splunk auditing for Estimated Pay update CY and CY+1

- app/uk/gov/hmrc/tai/controllers/income/IncomeController.scala
- test/uk/gov/hmrc/tai/controllers/income/IncomeControllerSpec.scala
> ST-484: Updated IncomeController to clear cache on update

- README.md
- docs/taxaccount/tax-free-amount-comparison.md
> ST-412:New section of read me added for tax free amount comparison

- project/plugins.sbt
> Upgrade play to 2.15.19

- app/uk/gov/hmrc/tai/calculators/EstimatedPayCalculator.scala
- app/uk/gov/hmrc/tai/calculators/TaxCalculator.scala
- app/uk/gov/hmrc/tai/connectors/CacheConnector.scala
- app/uk/gov/hmrc/tai/controllers/TaiController.scala
- app/uk/gov/hmrc/tai/model/api/TaxCodeSummary.scala
- app/uk/gov/hmrc/tai/model/nps/NpsTaxAccount.scala
- app/uk/gov/hmrc/tai/model/tai/TaxYear.scala
- app/uk/gov/hmrc/tai/model/templates/CloseBankAccount.scala
- app/uk/gov/hmrc/tai/modules/LocalGuiceModule.scala
- app/uk/gov/hmrc/tai/service/AutoUpdatePayService.scala
- app/uk/gov/hmrc/tai/service/TaiService.scala
- app/uk/gov/hmrc/tai/service/TaxCodeChangeService.scala
- app/uk/gov/hmrc/tai/templates/RemoveBankAccountIform.scala.html
- project/MicroServiceBuild.scala
- test/data/RTIData.scala
- test/uk/gov/hmrc/tai/calculators/EstimatedPayCalculatorSpec.scala
- test/uk/gov/hmrc/tai/calculators/TaxCalculatorSpec.scala
- test/uk/gov/hmrc/tai/connectors/CacheConnectorSpec.scala
- test/uk/gov/hmrc/tai/model/api/TaxCodeChangeSpec.scala
- test/uk/gov/hmrc/tai/model/nps/NpsEmploymentSpec.scala
- test/uk/gov/hmrc/tai/model/nps/NpsIabdSummarySpec.scala
- test/uk/gov/hmrc/tai/model/nps/NpsTaxAccountSpec.scala
- test/uk/gov/hmrc/tai/model/tai/TaxYearSpec.scala
- test/uk/gov/hmrc/tai/repositories/EmploymentRepositorySpec.scala
- test/uk/gov/hmrc/tai/service/EmploymentServiceSpec.scala
- test/uk/gov/hmrc/tai/service/PensionProviderServiceSpec.scala
- test/uk/gov/hmrc/tai/service/TaiServiceSpec.scala
- test/uk/gov/hmrc/tai/service/TaxCodeChangeServiceImplSpec.scala
- test/uk/gov/hmrc/tai/service/TaxFreeAmountComparisonServiceSpec.scala
- test/uk/gov/hmrc/tai/templates/RemoveBankAccountIformSpec.scala
> Update bootstrap-play-25 to v4.7.0

- project/MicroServiceBuild.scala
- test/uk/gov/hmrc/tai/controllers/FakeTaiPlayApplication.scala
> Update hmrctest to v3.3.0 and scalatestplus-play to v2.0.0

- app/uk/gov/hmrc/tai/config/ApplicationConfig.scala
- app/uk/gov/hmrc/tai/controllers/taxCodeChange/TaxCodeChangeController.scala
- conf/application.conf
- test/uk/gov/hmrc/tai/controllers/taxCodeChange/TaxCodeChangeControllerSpec.scala
> Remove Tax Code Change Toggle

- app/uk/gov/hmrc/tai/controllers/taxCodeChange/TaxCodeChangeController.scala
- app/uk/gov/hmrc/tai/model/TaxCodeHistory.scala
- app/uk/gov/hmrc/tai/service/TaxCodeChangeService.scala
> Added more logs to tax code change service

- app/uk/gov/hmrc/tai/connectors/CacheConnector.scala
- project/MicroServiceBuild.scala
- test/uk/gov/hmrc/tai/connectors/CacheConnectorSpec.scala
Change in API here - https://github.com/hmrc/ReactiveMongo/compare/v0.12.1...master
> Upgrade mongo caching from 5.0.0 to 5.6.0

- project/MicroServiceBuild.scala
- project/build.properties
- project/plugins.sbt
> Dep-Upgrade: Upgraded library dependencies to latest version

- app/uk/gov/hmrc/tai/repositories/EmploymentRepository.scala
- app/uk/gov/hmrc/tai/repositories/IncomeRepository.scala
> Add logs for CY+1

- app/uk/gov/hmrc/tai/model/domain/formatters/income/TaxCodeIncomeHodFormatters.scala
> ST-557: Add logging for 0 tax code income

- app/uk/gov/hmrc/tai/repositories/EmploymentRepository.scala
- app/uk/gov/hmrc/tai/repositories/IncomeRepository.scala
> removeRedundantLogs: Remove redundant logs

- app/uk/gov/hmrc/tai/config/ApplicationConfig.scala
- app/uk/gov/hmrc/tai/connectors/ApplicationUrls.scala
- app/uk/gov/hmrc/tai/connectors/TaxAccountConnector.scala
- conf/application.conf
- test/uk/gov/hmrc/tai/connectors/ApplicationUrlsSpec.scala
- test/uk/gov/hmrc/tai/connectors/TaxAccountConnectorSpec.scala
> Confirmed api toggle

- app/uk/gov/hmrc/tai/connectors/TaxAccountConnector.scala
- test/uk/gov/hmrc/tai/connectors/TaxAccountConnectorSpec.scala
> DES-Auth-fix: Fix for 403

- app/uk/gov/hmrc/tai/connectors/ApplicationUrls.scala
- app/uk/gov/hmrc/tai/model/domain/formatters/income/TaxCodeIncomeHodFormatters.scala
> Logging employment status

- app/uk/gov/hmrc/tai/connectors/NpsConnector.scala
- app/uk/gov/hmrc/tai/model/enums/APITypes.scala
- app/uk/gov/hmrc/tai/service/expenses/FlatRateExpensesService.scala
- test/uk/gov/hmrc/tai/connectors/NpsConnectorSpec.scala
- test/uk/gov/hmrc/tai/service/expenses/FlatRateExpensesServiceSpec.scala
> add NPS FRE update function

- app/uk/gov/hmrc/tai/controllers/expenses/FlatRateExpensesController.scala
- test/uk/gov/hmrc/tai/controllers/expenses/FlatRateExpensesControllerSpec.scala
> EE-388: Updated FlatRateExpensesData to accept 204 and 202

- app/uk/gov/hmrc/tai/connectors/ApplicationUrls.scala
- app/uk/gov/hmrc/tai/model/domain/formatters/income/TaxCodeIncomeHodFormatters.scala
> ST-582 Revert "Logging employment status"

- app/uk/gov/hmrc/tai/connectors/DesConnector.scala
- app/uk/gov/hmrc/tai/connectors/NpsConnector.scala
- app/uk/gov/hmrc/tai/controllers/expenses/FlatRateExpensesController.scala
- app/uk/gov/hmrc/tai/model/UpdateIabdDataModel.scala
- app/uk/gov/hmrc/tai/model/UpdateIabdFlatRateExpense.scala
- app/uk/gov/hmrc/tai/service/expenses/FlatRateExpensesService.scala
- test/uk/gov/hmrc/tai/connectors/DesConnectorSpec.scala
- test/uk/gov/hmrc/tai/connectors/NpsConnectorSpec.scala
- test/uk/gov/hmrc/tai/controllers/expenses/FlatRateExpensesControllerSpec.scala
- test/uk/gov/hmrc/tai/model/UpdateIabdFlatRateExpenseSpec.scala
- test/uk/gov/hmrc/tai/service/expenses/FlatRateExpensesServiceSpec.scala
> update FRE POST

- app/uk/gov/hmrc/tai/connectors/DesConnector.scala
- app/uk/gov/hmrc/tai/service/expenses/FlatRateExpensesService.scala
- test/uk/gov/hmrc/tai/connectors/DesConnectorSpec.scala
> EE: FRE Endpoint update

- app/uk/gov/hmrc/tai/model/domain/formatters/income/TaxCodeIncomeHodFormatters.scala
> Added employment status logging

- app/uk/gov/hmrc/tai/model/domain/formatters/income/TaxCodeIncomeHodFormatters.scala
> employment-status-logging: removal of toString() on logging

- app/uk/gov/hmrc/tai/connectors/ApplicationUrls.scala
- test/uk/gov/hmrc/tai/connectors/ApplicationUrlsSpec.scala
- test/uk/gov/hmrc/tai/connectors/TaxAccountConnectorSpec.scala
> Temporarily binned confirmedApi toggle

- app/uk/gov/hmrc/tai/model/domain/formatters/income/TaxCodeIncomeHodFormatters.scala
> Removed Logger.warn from TaxCodeIncomeHodFormatters

- app/uk/gov/hmrc/tai/connectors/ApplicationUrls.scala
- test/uk/gov/hmrc/tai/connectors/ApplicationUrlsSpec.scala
- test/uk/gov/hmrc/tai/connectors/TaxAccountConnectorSpec.scala
> Revert "Temporarily binned confirmedApi toggle"

- app/uk/gov/hmrc/tai/connectors/ApplicationUrls.scala
- test/uk/gov/hmrc/tai/connectors/ApplicationUrlsSpec.scala
- test/uk/gov/hmrc/tai/connectors/TaxAccountConnectorSpec.scala
> Revert "Revert "Temporarily binned confirmedApi toggle""

- app/uk/gov/hmrc/tai/connectors/ApplicationUrls.scala
- test/uk/gov/hmrc/tai/connectors/ApplicationUrlsSpec.scala
- test/uk/gov/hmrc/tai/connectors/TaxAccountConnectorSpec.scala
> Revert "Revert "Revert "Temporarily binned confirmedApi toggle"""

- app/uk/gov/hmrc/tai/model/IabdUpdateAmount.scala
> ST-483 Gross and net amounts can be larger than 999999

- test/uk/gov/hmrc/tai/service/AutoUpdatePayServiceSpec.scala
> ST-leapYearBug: Resolve bug caused by leap year 

- test/uk/gov/hmrc/tai/calculators/EstimatedPayCalculatorSpec.scala
- test/uk/gov/hmrc/tai/service/AutoUpdatePayServiceSpec.scala
> leapYearFixPt2: Updated tests to fix dates changing due to leap year

- app/uk/gov/hmrc/tai/connectors/HttpHandler.scala
- test/uk/gov/hmrc/tai/connectors/HttpHandlerSpec.scala
> [HMA-354][PH] Fix custom http response handling

- app/uk/gov/hmrc/tai/connectors/HttpHandler.scala
- test/uk/gov/hmrc/tai/connectors/HttpHandlerSpec.scala
> Revert "[HMA-354][PH] Fix custom http response handling"

- app/uk/gov/hmrc/tai/connectors/ApplicationUrls.scala
- test/uk/gov/hmrc/tai/connectors/ApplicationUrlsSpec.scala
- test/uk/gov/hmrc/tai/connectors/TaxAccountConnectorSpec.scala
> "Temporarily binned confirmedApi toggle"

- README.md
> testing tagging

- README.md
> Revert "testing tagging"

- app/uk/gov/hmrc/tai/connectors/HttpHandler.scala
- test/uk/gov/hmrc/tai/connectors/HttpHandlerSpec.scala
> Revert "Revert "[HMA-354][PH] Fix custom http response handling""

- app/uk/gov/hmrc/tai/repositories/PersonRepository.scala
- test/uk/gov/hmrc/tai/repositories/PersonRepositorySpec.scala
> personCacheFix: Fixed caching person details so that cache is used

- app/uk/gov/hmrc/tai/config/ApplicationConfig.scala
- app/uk/gov/hmrc/tai/connectors/CacheConnector.scala
- app/uk/gov/hmrc/tai/connectors/Caching.scala
- app/uk/gov/hmrc/tai/metrics/Metrics.scala
- app/uk/gov/hmrc/tai/repositories/IabdRepository.scala
- app/uk/gov/hmrc/tai/repositories/TaxAccountRepository.scala
- conf/application.conf
- test/uk/gov/hmrc/tai/connectors/CacheConnectorSpec.scala
- test/uk/gov/hmrc/tai/connectors/CachingSpec.scala
- test/uk/gov/hmrc/tai/metrics/MetricsSpec.scala
- test/uk/gov/hmrc/tai/repositories/IabdRepositorySpec.scala
- test/uk/gov/hmrc/tai/repositories/TaxAccountRepositorySpec.scala
> CacheMetrics: Add metrics for cache hits and misses

- app/uk/gov/hmrc/tai/connectors/CacheConnector.scala
> Create one instance of the CacheRepository

- README.md
- app/uk/gov/hmrc/tai/binders/TaxCodeIncomeComponentBinder.scala
- app/uk/gov/hmrc/tai/binders/TaxCodeIncomeStatusBinder.scala
- app/uk/gov/hmrc/tai/controllers/income/IncomeController.scala
- app/uk/gov/hmrc/tai/model/api/ApiFormats.scala
- app/uk/gov/hmrc/tai/model/domain/TaxComponentType.scala
- app/uk/gov/hmrc/tai/model/domain/income/IncomeSource.scala
- app/uk/gov/hmrc/tai/model/domain/income/TaxCodeIncome.scala
- app/uk/gov/hmrc/tai/service/IncomeService.scala
- conf/app.routes
- docs/incomes/matched-incomes.md
- docs/incomes/nonmatching-incomes.md
- it/uk/gov/hmrc/tai/integration/cache/connectors/CacheConnectorItSpec.scala
- project/Microservice.scala
- test/uk/gov/hmrc/tai/controllers/income/IncomeControllerSpec.scala
- test/uk/gov/hmrc/tai/service/IncomeServiceSpec.scala
> Revert "Revert "[NGC-4566] - Add taxCodeIncomes and employments to tai from the frontend""

- app/uk/gov/hmrc/tai/connectors/CacheConnector.scala
- test/uk/gov/hmrc/tai/connectors/CacheConnectorSpec.scala
> DI cacherepository

- app/uk/gov/hmrc/tai/model/domain/income/TaxCodeIncome.scala
- app/uk/gov/hmrc/tai/service/IncomeService.scala
- docs/incomes/matched-incomes.md
- test/uk/gov/hmrc/tai/service/IncomeServiceSpec.scala
- [/] Unit tests passing
- [/] Coverage reached
- [/] Acceptance tests passing
> [HMA-1095][PH] Updates to perform filtering correctly on TaxCodeIncomes as part of mobile work

- app/uk/gov/hmrc/tai/connectors/ApplicationUrls.scala
- conf/application.conf
> remove new line

- app/uk/gov/hmrc/tai/connectors/BaseConnector.scala
- app/uk/gov/hmrc/tai/connectors/HttpHandler.scala
> Ddcnos 5455

- README.md
- docs/employee-expenses/get-employee-expenses.md
- docs/employee-expenses/update-employee-expenses.md
> EE-591 added new endpoints into readme file

- app/uk/gov/hmrc/tai/model/domain/benefits/Benefits.scala
- app/uk/gov/hmrc/tai/model/templates/RemoveCompanyBenefitViewModel.scala
- app/uk/gov/hmrc/tai/service/AutoUpdatePayService.scala
- app/uk/gov/hmrc/tai/service/benefits/BenefitsService.scala
- app/uk/gov/hmrc/tai/templates/RemoveCompanyBenefitIForm.scala.html
- project/Microservice.scala
- test/uk/gov/hmrc/tai/controllers/benefits/BenefitsControllerSpec.scala
- test/uk/gov/hmrc/tai/model/templates/RemoveCompanyBenefitViewModelSpec.scala
- test/uk/gov/hmrc/tai/service/benefits/BenefitsServiceSpec.scala
- test/uk/gov/hmrc/tai/templates/RemoveCompanyBenefitIFormSpec.scala
> Ddcnls 6534

- app/uk/gov/hmrc/tai/repositories/EmploymentRepository.scala
> DDCNOS-5754:Added extra logging to cater for Not Found issue

- app/uk/gov/hmrc/tai/controllers/EmploymentsController.scala
- app/uk/gov/hmrc/tai/model/error/EmploymentRetrievalError.scala
- app/uk/gov/hmrc/tai/repositories/EmploymentRepository.scala
- app/uk/gov/hmrc/tai/service/EmploymentService.scala
- app/uk/gov/hmrc/tai/service/PensionProviderService.scala
- docs/employments/id-employments.md
- resources/public/api/conf/1.0/application.raml
- test/uk/gov/hmrc/tai/controllers/EmploymentsControllerSpec.scala
- test/uk/gov/hmrc/tai/repositories/EmploymentRepositorySpec.scala
- test/uk/gov/hmrc/tai/service/EmploymentServiceSpec.scala
- test/uk/gov/hmrc/tai/service/IncomeServiceSpec.scala
- test/uk/gov/hmrc/tai/service/PensionProviderServiceSpec.scala
> DDCNOS-5985: Fix 404 error due to RTI unavailability

- app/uk/gov/hmrc/tai/connectors/BaseConnector.scala
> DDCNOS: fix wrongly created new header

- app/uk/gov/hmrc/tai/connectors/BbsiConnector.scala
- app/uk/gov/hmrc/tai/connectors/RtiConnector.scala
- app/uk/gov/hmrc/tai/connectors/TaxCodeChangeConnector.scala
- app/uk/gov/hmrc/tai/service/TaxCodeChangeService.scala
- test/uk/gov/hmrc/tai/connectors/RtiConnectorSpec.scala
- test/uk/gov/hmrc/tai/connectors/TaxCodeChangeConnectorSpec.scala
- test/uk/gov/hmrc/tai/service/TaxCodeChangeServiceImplSpec.scala
> DDCNOS: fixed header carrier extra headers

- app/uk/gov/hmrc/tai/connectors/BbsiConnector.scala
- app/uk/gov/hmrc/tai/connectors/RtiConnector.scala
- app/uk/gov/hmrc/tai/connectors/TaxCodeChangeConnector.scala
- app/uk/gov/hmrc/tai/service/TaxCodeChangeService.scala
- test/uk/gov/hmrc/tai/connectors/RtiConnectorSpec.scala
- test/uk/gov/hmrc/tai/connectors/TaxCodeChangeConnectorSpec.scala
- test/uk/gov/hmrc/tai/service/TaxCodeChangeServiceImplSpec.scala
> Revert "DDCNOS: fixed header carrier extra headers"

- app/uk/gov/hmrc/tai/controllers/predicates/AuthenticationPredicate.scala
- test/uk/gov/hmrc/tai/controllers/predicates/AuthenticationPredicateSpec.scala
> DDCNL 770 - recover on AuthorisationException

- app/uk/gov/hmrc/tai/model/templates/PdfSubmission.scala
- test/uk/gov/hmrc/tai/templates/PdfSubmissionMetadataSpec.scala
> Ensure submission references are unique

- app/uk/gov/hmrc/tai/controllers/predicates/AuthenticationPredicate.scala
- conf/application.conf
- project/MicroServiceBuild.scala
- test/uk/gov/hmrc/tai/controllers/predicates/AuthenticationPredicateSpec.scala
> Ddcnl 1625

- app/uk/gov/hmrc/tai/service/FileUploadService.scala
> Log as error when a file fails to upload

- app/uk/gov/hmrc/tai/connectors/ApplicationUrls.scala
- app/uk/gov/hmrc/tai/connectors/CitizenDetailsConnector.scala
- app/uk/gov/hmrc/tai/model/ETag.scala
- app/uk/gov/hmrc/tai/service/FileUploadService.scala
- app/uk/gov/hmrc/tai/service/IncomeService.scala
- test/uk/gov/hmrc/tai/connectors/CitizenDetailsConnectorSpec.scala
- test/uk/gov/hmrc/tai/model/ETagSpec.scala
- test/uk/gov/hmrc/tai/service/IncomeServiceSpec.scala
- test/uk/gov/hmrc/tai/util/WireMockHelper.scala
> DDCNL-1891

- README.md
> DDCNL-Update Readme

- app/uk/gov/hmrc/tai/connectors/CacheConnector.scala
- project/MicroServiceBuild.scala
- test/uk/gov/hmrc/tai/connectors/CacheConnectorSpec.scala
> DDCNL-2570 | mongo upgrade

- app/uk/gov/hmrc/tai/controllers/EmploymentsController.scala
- app/uk/gov/hmrc/tai/model/error/EmploymentRetrievalError.scala
- app/uk/gov/hmrc/tai/repositories/EmploymentRepository.scala
- test/uk/gov/hmrc/tai/controllers/EmploymentsControllerSpec.scala
- test/uk/gov/hmrc/tai/repositories/EmploymentRepositorySpec.scala
> DDCNL-2427

- app/uk/gov/hmrc/tai/repositories/EmploymentRepository.scala
- conf/application.conf
- it/uk/gov/hmrc/tai/integration/EmploymentRepositoryItSpec.scala
- test/uk/gov/hmrc/tai/repositories/EmploymentRepositorySpec.scala
> DDCNL-2466

- test/uk/gov/hmrc/tai/connectors/BaseConnectorSpec.scala
- test/uk/gov/hmrc/tai/connectors/CacheConnectorSpec.scala
- test/uk/gov/hmrc/tai/connectors/CitizenDetailsConnectorSpec.scala
- test/uk/gov/hmrc/tai/connectors/CompanyCarConnectorSpec.scala
- test/uk/gov/hmrc/tai/connectors/ConnectorBaseSpec.scala
- test/uk/gov/hmrc/tai/connectors/DesConnectorSpec.scala
- test/uk/gov/hmrc/tai/connectors/FileUploadConnectorSpec.scala
- test/uk/gov/hmrc/tai/connectors/IabdConnectorSpec.scala
- test/uk/gov/hmrc/tai/connectors/NpsConnectorSpec.scala
- test/uk/gov/hmrc/tai/connectors/PdfConnectorSpec.scala
- test/uk/gov/hmrc/tai/connectors/RtiConnectorSpec.scala
- test/uk/gov/hmrc/tai/connectors/TaxAccountConnectorSpec.scala
- test/uk/gov/hmrc/tai/connectors/TaxCodeChangeConnectorSpec.scala
- test/uk/gov/hmrc/tai/model/api/ApiFormatsSpec.scala
- test/uk/gov/hmrc/tai/util/WireMockHelper.scala
> DDCNL-2834 | Refactor connector tests to use Wiremock

- build.sbt
- it/uk/gov/hmrc/tai/integration/TaiEmbeddedServer.scala
- it/uk/gov/hmrc/tai/integration/cache/connectors/CacheConnectorItSpec.scala
- project/plugins.sbt
- test/uk/gov/hmrc/tai/model/api/ApiFormatsSpec.scala
> DDCNL-2932: Auto generate integration tests license headers

- app/uk/gov/hmrc/tai/controllers/predicates/AuthenticationPredicate.scala
> DDCNL-3687 - Requiring CL200

- build.sbt
> DDCNL-1339: Fixed scoverage/scala incompatibility issue

- app/uk/gov/hmrc/tai/connectors/BbsiConnector.scala
- app/uk/gov/hmrc/tai/connectors/HttpHandler.scala
- app/uk/gov/hmrc/tai/controllers/income/BbsiController.scala
- app/uk/gov/hmrc/tai/metrics/HasMetrics.scala
- app/uk/gov/hmrc/tai/model/domain/formatters/BbsiHodFormatters.scala
- app/uk/gov/hmrc/tai/repositories/BbsiRepository.scala
- app/uk/gov/hmrc/tai/repositories/IncomeRepository.scala
- app/uk/gov/hmrc/tai/service/BbsiService.scala
- conf/application.conf
- project/AppDependencies.scala
- test/uk/gov/hmrc/tai/connectors/BbsiConnectorSpec.scala
- test/uk/gov/hmrc/tai/connectors/ConnectorBaseSpec.scala
- test/uk/gov/hmrc/tai/connectors/HttpHandlerSpec.scala
- test/uk/gov/hmrc/tai/controllers/income/BbsiControllerSpec.scala
- test/uk/gov/hmrc/tai/metrics/HasMetricsSpec.scala
- test/uk/gov/hmrc/tai/repositories/BbsiRepositorySpec.scala
- test/uk/gov/hmrc/tai/repositories/IncomeRepositorySpec.scala
- test/uk/gov/hmrc/tai/service/BbsiServiceSpec.scala
- test/uk/gov/hmrc/tai/util/TestMetrics.scala
> Ddcnl 3241

- project/plugins.sbt
> DDCNL-3847 | removing bintray

- project/plugins.sbt
> Revert "DDCNL-3847 | removing bintray"

- project/plugins.sbt
> Revert "Revert "DDCNL-3847 | removing bintray""

- app/uk/gov/hmrc/tai/connectors/CitizenDetailsConnector.scala
- app/uk/gov/hmrc/tai/model/domain/Person.scala
- app/uk/gov/hmrc/tai/model/domain/formatters/income/TaxCodeIncomeHodFormatters.scala
- app/uk/gov/hmrc/tai/repositories/PersonRepository.scala
- conf/application.conf
- test/uk/gov/hmrc/tai/connectors/CitizenDetailsConnectorSpec.scala
- test/uk/gov/hmrc/tai/controllers/PersonControllerSpec.scala
- test/uk/gov/hmrc/tai/repositories/PersonRepositorySpec.scala
> Revert "DDCNL-3547"

- app/uk/gov/hmrc/tai/connectors/CitizenDetailsConnector.scala
- app/uk/gov/hmrc/tai/model/domain/Person.scala
- app/uk/gov/hmrc/tai/repositories/EmploymentRepository.scala
- app/uk/gov/hmrc/tai/repositories/PersonRepository.scala
- test/uk/gov/hmrc/tai/connectors/CitizenDetailsConnectorSpec.scala
- test/uk/gov/hmrc/tai/controllers/PersonControllerSpec.scala
- test/uk/gov/hmrc/tai/repositories/PersonRepositorySpec.scala
> DDCNL-3547: Added MCI flag for locked journey and refactored key name

- app/uk/gov/hmrc/tai/controllers/taxCodeChange/TaxCodeChangeController.scala
- app/uk/gov/hmrc/tai/controllers/taxCodeChange/TaxCodeChangeIabdComparisonController.scala
- it/uk/gov/hmrc/tai/integration/TaxCodeChangeSpec.scala
- it/uk/gov/hmrc/tai/integration/TaxCodeLatestSpec.scala
- it/uk/gov/hmrc/tai/integration/TaxCodeMismatchSpec.scala
- it/uk/gov/hmrc/tai/integration/TaxFreeAmountComparisonSpec.scala
- test/uk/gov/hmrc/tai/controllers/taxCodeChange/TaxCodeChangeControllerSpec.scala
- test/uk/gov/hmrc/tai/controllers/taxCodeChange/TaxCodeChangeIabdComparisonControllerSpec.scala
> Ddcnl 3613

- project/build.properties
> Upgraded sbt version

- it/uk/gov/hmrc/tai/integration/GetEmployeeExpensesSpec.scala
- it/uk/gov/hmrc/tai/integration/GetEmploymentsSpec.scala
- it/uk/gov/hmrc/tai/integration/PostEmployeeExpensesSpec.scala
- it/uk/gov/hmrc/tai/integration/PutWorkingFromHomeEmployeeExpenses.scala
- it/uk/gov/hmrc/tai/integration/TaxAccountSummarySpec.scala
- it/uk/gov/hmrc/tai/integration/TaxCodeChangeSpec.scala
- it/uk/gov/hmrc/tai/integration/TaxCodeLatestSpec.scala
- it/uk/gov/hmrc/tai/integration/TaxCodeMismatchSpec.scala
- it/uk/gov/hmrc/tai/integration/TaxFreeAmountComparisonSpec.scala
- it/uk/gov/hmrc/tai/integration/UpdateIncomeSpec.scala
- it/uk/gov/hmrc/tai/integration/cache/connectors/CacheConnectorItSpec.scala
- it/uk/gov/hmrc/tai/integration/utils/FileHelper.scala
- it/uk/gov/hmrc/tai/integration/utils/IntegrationSpec.scala
- it/uk/gov/hmrc/tai/integration/utils/WireMockHelper.scala
> DDCNL: update license header

- app/uk/gov/hmrc/tai/config/ApplicationConfig.scala
- conf/application.conf
> DDCNL-5258: Deleted unused toggle

- app/uk/gov/hmrc/tai/service/IncomeService.scala
- test/uk/gov/hmrc/tai/service/IncomeServiceSpec.scala
> PAYEE-81 Implemented return status from employment API

- app/uk/gov/hmrc/tai/service/IncomeService.scala
- test/uk/gov/hmrc/tai/service/IncomeServiceSpec.scala
This reverts commit 7ba09b0c01d95c3ed1fe183024607922f54c5b82.
> Revert "PAYEE-80 Implemented return status from employment API (#223)"

- .gitignore
- app/uk/gov/hmrc/tai/connectors/Caching.scala
- app/uk/gov/hmrc/tai/connectors/TaxCodeChangeConnector.scala
- app/uk/gov/hmrc/tai/repositories/TaxCodeChangeRepository.scala
- app/uk/gov/hmrc/tai/service/TaxCodeChangeService.scala
- app/uk/gov/hmrc/tai/util/TaiConstants.scala
- test/uk/gov/hmrc/tai/connectors/CachingSpec.scala
- test/uk/gov/hmrc/tai/service/TaxCodeChangeServiceImplSpec.scala
> PAYEE-148 - Caching the tax code change API call

- app/uk/gov/hmrc/tai/service/IncomeService.scala
- test/uk/gov/hmrc/tai/service/IncomeServiceSpec.scala
> PAYEE-81: uses taxCodeIncomes.status if the employment api fails

- app/uk/gov/hmrc/tai/controllers/JourneyCacheController.scala
- test/uk/gov/hmrc/tai/controllers/JourneyCacheControllerSpec.scala
> Payee 68 tai journey cache returns a 404 on success

- app/uk/gov/hmrc/tai/config/ApplicationConfig.scala
- app/uk/gov/hmrc/tai/connectors/CacheConnector.scala
- app/uk/gov/hmrc/tai/connectors/CacheId.scala
- app/uk/gov/hmrc/tai/controllers/JourneyCacheController.scala
- app/uk/gov/hmrc/tai/repositories/JourneyCacheRepository.scala
- conf/app.routes
- conf/application.conf
- it/uk/gov/hmrc/tai/integration/cache/connectors/CacheConnectorItSpec.scala
- project/AppDependencies.scala
- test/uk/gov/hmrc/tai/connectors/CacheConnectorSpec.scala
- test/uk/gov/hmrc/tai/controllers/JourneyCacheControllerSpec.scala
- test/uk/gov/hmrc/tai/mocks/MockAuthenticationPredicate.scala
- test/uk/gov/hmrc/tai/repositories/JourneyCacheRepositorySpec.scala
> PAYEE-341 - New methods to cache an updated income amount

- app/uk/gov/hmrc/tai/util/TaiConstants.scala
> TempPipelineFix

- app/uk/gov/hmrc/tai/model/tai/TaxYear.scala
- app/uk/gov/hmrc/tai/model/templates/PdfSubmission.scala
- app/uk/gov/hmrc/tai/util/TaiConstants.scala
- test/uk/gov/hmrc/tai/model/nps/NpsTaxAccountSpec.scala
> PAYEE-720 - Getting timezone from TaiConstants

- app/uk/gov/hmrc/tai/controllers/JourneyCacheController.scala
- app/uk/gov/hmrc/tai/controllers/testOnly/TestOnlyCacheController.scala
- app/uk/gov/hmrc/tai/repositories/JourneyCacheRepository.scala
- conf/app.routes
- conf/testOnlyDoNotUseInAppConf.routes
- test/uk/gov/hmrc/tai/controllers/JourneyCacheControllerSpec.scala
- test/uk/gov/hmrc/tai/controllers/testOnly/TestOnlyCacheControllerSpec.scala
- test/uk/gov/hmrc/tai/repositories/JourneyCacheRepositorySpec.scala
> Payee 594: Facilitator to drop the cache for acceptance tests

- test/uk/gov/hmrc/tai/model/rti/RtiPaymentSpec.scala
> fixed tests

- test/uk/gov/hmrc/tai/connectors/DesConnectorSpec.scala
- test/uk/gov/hmrc/tai/model/rti/RtiPaymentSpec.scala
> removed unused calculation

- app/uk/gov/hmrc/tai/service/TaxCodeChangeService.scala
- app/uk/gov/hmrc/tai/util/TaiConstants.scala
- test/uk/gov/hmrc/tai/service/TaxCodeChangeServiceImplSpec.scala
> PAYEE-791 - Fixing bug in code, see ticket for info

- app/uk/gov/hmrc/tai/connectors/RtiConnector.scala
- test/uk/gov/hmrc/tai/connectors/RtiConnectorSpec.scala
> Payee 1159

- app/uk/gov/hmrc/tai/connectors/TaiCacheRepository.scala
> MongoTtl - Reverting back to previous TTL

- app/uk/gov/hmrc/tai/connectors/CacheConnector.scala
> PAYEE-1169 - Using optionT in the cacheConnector

- app/uk/gov/hmrc/tai/calculators/EstimatedPayCalculator.scala
- app/uk/gov/hmrc/tai/model/enums/PayFreq.scala
- test/uk/gov/hmrc/tai/calculators/EstimatedPayCalculatorSpec.scala
- test/uk/gov/hmrc/tai/model/PayDetailsSpec.scala
> PAYEE-1038: Update your estimated income - add 4 weekly as an option

- app/uk/gov/hmrc/tai/templates/EmploymentIForm.scala.html
- app/uk/gov/hmrc/tai/templates/IncorrectBankAccountIform.scala.html
- app/uk/gov/hmrc/tai/templates/PensionProviderIForm.scala.html
- app/uk/gov/hmrc/tai/templates/PersonDetails.scala.html
- app/uk/gov/hmrc/tai/templates/QueryYearDetails.scala.html
- app/uk/gov/hmrc/tai/templates/RemoveBankAccountIform.scala.html
- app/uk/gov/hmrc/tai/templates/RemoveCompanyBenefitIForm.scala.html
- it/uk/gov/hmrc/tai/integration/GetEmployeeExpensesSpec.scala
- it/uk/gov/hmrc/tai/integration/GetEmploymentsSpec.scala
- it/uk/gov/hmrc/tai/integration/PostEmployeeExpensesSpec.scala
- it/uk/gov/hmrc/tai/integration/PutWorkingFromHomeEmployeeExpenses.scala
- it/uk/gov/hmrc/tai/integration/TaxAccountSummarySpec.scala
- it/uk/gov/hmrc/tai/integration/TaxCodeChangeSpec.scala
- it/uk/gov/hmrc/tai/integration/TaxCodeLatestSpec.scala
- it/uk/gov/hmrc/tai/integration/TaxCodeMismatchSpec.scala
- it/uk/gov/hmrc/tai/integration/TaxFreeAmountComparisonSpec.scala
- it/uk/gov/hmrc/tai/integration/UpdateIncomeSpec.scala
- it/uk/gov/hmrc/tai/integration/cache/connectors/TaiCacheRepositoryItSpec.scala
- it/uk/gov/hmrc/tai/integration/utils/FileHelper.scala
- it/uk/gov/hmrc/tai/integration/utils/IntegrationSpec.scala
- it/uk/gov/hmrc/tai/integration/utils/WireMockHelper.scala
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
> PAYEE-update-dependencies: update sbt plugins and sbt version

- app/uk/gov/hmrc/tai/repositories/IncomeRepository.scala
- app/uk/gov/hmrc/tai/repositories/TaxAccountSummaryRepository.scala
- app/uk/gov/hmrc/tai/service/IncomeService.scala
- app/uk/gov/hmrc/tai/service/TaxFreeAmountComparisonService.scala
> reduce concurrency

- app/uk/gov/hmrc/tai/model/TaxCodeHistory.scala
- app/uk/gov/hmrc/tai/repositories/cache/TaiCacheRepository.scala
- app/uk/gov/hmrc/tai/service/TaxCodeChangeService.scala
- test/uk/gov/hmrc/tai/service/TaxCodeChangeServiceImplSpec.scala
> fixed  bug in caching

- app/uk/gov/hmrc/tai/connectors/IabdConnector.scala
- app/uk/gov/hmrc/tai/controllers/TaxAccountSummaryController.scala
- app/uk/gov/hmrc/tai/repositories/IabdRepository.scala
- it/uk/gov/hmrc/tai/integration/GetEmployeeExpensesSpec.scala
- it/uk/gov/hmrc/tai/integration/TaxAccountSummarySpec.scala
- test/uk/gov/hmrc/tai/repositories/IabdRepositorySpec.scala
> Add 404 status from iabds to cache

- app/uk/gov/hmrc/tai/service/IncomeService.scala
> DDCNL: add todo

- app/uk/gov/hmrc/tai/model/nps2/TaxAccount.scala
> fixed scaladoc errors

- app/uk/gov/hmrc/tai/model/IabdUpdateAmount.scala
- app/uk/gov/hmrc/tai/model/UpdateIabdEmployeeExpense.scala
- app/uk/gov/hmrc/tai/model/nps/NpsTaxAccount.scala
- app/uk/gov/hmrc/tai/model/nps/NpsTotalLiability.scala
- app/uk/gov/hmrc/tai/model/nps2/TaxBand.scala
- app/uk/gov/hmrc/tai/model/rti/PayFrequency.scala
- app/uk/gov/hmrc/tai/model/rti/RtiData.scala
- app/uk/gov/hmrc/tai/model/rti/RtiEmployment.scala
- app/uk/gov/hmrc/tai/model/rti/RtiPayment.scala
- test/uk/gov/hmrc/tai/model/nps/TaxModelSpec.scala
- test/uk/gov/hmrc/tai/rti/RtiGenerator.scala
> scaladoc fixes

- app/uk/gov/hmrc/tai/service/TaxCodeChangeService.scala
- test/resources/logback-test.xml
- test/uk/gov/hmrc/tai/service/TaxCodeChangeServiceImplSpec.scala
> Fixed tax code change

- app/uk/gov/hmrc/tai/service/TaxCodeChangeService.scala
- conf/logback.xml
- it/uk/gov/hmrc/tai/integration/TaxCodeChangeSpec.scala
- it/uk/gov/hmrc/tai/integration/resources/nino1/iabds.json
- it/uk/gov/hmrc/tai/integration/resources/nino1/tax-account.json
- it/uk/gov/hmrc/tai/integration/resources/nino1/tax-code-history.json
- test/uk/gov/hmrc/tai/service/TaxCodeChangeServiceImplSpec.scala
> reverting the work in PAYEE-791 and putting a proper fix

- app/uk/gov/hmrc/tai/model/domain/formatters/IncomeCategoryHodFormatters.scala
- it/uk/gov/hmrc/tai/integration/resources/taxAccount.json
- project/plugins.sbt
- test/uk/gov/hmrc/tai/model/domain/formatters/IncomeCategoryHodFormattersSpec.scala
- test/uk/gov/hmrc/tai/repositories/TotalTaxRepositorySpec.scala
> DDCNL-7820 Refactored taxBand reads

- app/uk/gov/hmrc/tai/config/ApplicationConfig.scala
- app/uk/gov/hmrc/tai/config/ApplicationStartUp.scala
- app/uk/gov/hmrc/tai/connectors/ApplicationUrls.scala
- app/uk/gov/hmrc/tai/connectors/IfConnector.scala
- app/uk/gov/hmrc/tai/connectors/deprecated/TaxCodeChangeFromDesConnector.scala
- app/uk/gov/hmrc/tai/model/admin/FeatureFlags.scala
- app/uk/gov/hmrc/tai/repositories/deprecated/TaxCodeChangeRepository.scala
- conf/application.conf
- it/uk/gov/hmrc/tai/integration/TaxCodeLatestSpec.scala
- it/uk/gov/hmrc/tai/integration/utils/IntegrationSpec.scala
- test/uk/gov/hmrc/tai/connectors/ConnectorBaseSpec.scala
- test/uk/gov/hmrc/tai/connectors/TaxCodeChangeFromDesConnectorSpec.scala
- test/uk/gov/hmrc/tai/repositories/TaxCodeChangeRepositorySpec.scala
- test/uk/gov/hmrc/tai/service/TaxCodeChangeServiceImplSpec.scala
> Ddcnl 7890

- app/uk/gov/hmrc/tai/config/ApplicationStartUp.scala
- app/uk/gov/hmrc/tai/model/admin/FeatureFlags.scala
- app/uk/gov/hmrc/tai/repositories/deprecated/TaxCodeChangeRepository.scala
- test/uk/gov/hmrc/tai/connectors/ConnectorBaseSpec.scala
- test/uk/gov/hmrc/tai/repositories/TaxCodeChangeRepositorySpec.scala
> DDCNL-7890v2

- app/uk/gov/hmrc/tai/model/domain/TaxComponentType.scala
- app/uk/gov/hmrc/tai/model/domain/formatters/taxComponents/TaxAccountHodFormatters.scala
- test/uk/gov/hmrc/tai/factory/TaxAccountHistoryFactory.scala
- test/uk/gov/hmrc/tai/repositories/CodingComponentRepositorySpec.scala
> DDCNL-8417 Added new BR code components

- app/uk/gov/hmrc/tai/controllers/ControllerErrorHandler.scala
- test/uk/gov/hmrc/tai/controllers/ControllerErrorHandlerSpec.scala
> DDCNL-8802: recover some exceptions

- app/uk/gov/hmrc/tai/connectors/TaxCodeHistoryConnector.scala
- build.sbt
- project/AppDependencies.scala
- project/plugins.sbt
> Changed IF header originatorId to originator-id

- app/uk/gov/hmrc/tai/connectors/EmploymentDetailsConnector.scala
- test/uk/gov/hmrc/tai/connectors/DefaultEmploymentDetailsConnectorSpec.scala
> Fixed auth for hip

- app/uk/gov/hmrc/tai/model/domain/calculation/TotalTaxHipReads.scala
- test/uk/gov/hmrc/tai/model/domain/calculation/TotalTaxHipReadsSpec.scala
- test/uk/gov/hmrc/tai/model/domain/calculation/TotalTaxSquidReadsSpec.scala
> 9508 Fix issue in totalLiabilityDetails field

- test/uk/gov/hmrc/tai/service/IabdServiceSpec.scala
> Uncomment UTs

- app/uk/gov/hmrc/tai/model/domain/IabdDetails.scala
- app/uk/gov/hmrc/tai/util/JsonHelper.scala
- test/uk/gov/hmrc/tai/service/IabdServiceSpec.scala
> DDCNL-9562 fixed bug when iabds response is empty

- app/uk/gov/hmrc/tai/model/api/EmploymentCollection.scala
- test/uk/gov/hmrc/tai/model/api/EmploymentCollectionSpec.scala
> Ddcnl 9563

- app/uk/gov/hmrc/tai/connectors/TaxAccountConnector.scala
- test/uk/gov/hmrc/tai/connectors/TaxAccountConnectorSpec.scala
> 9588 Throw not found exception if empty payload for tax account (hip)

- app/uk/gov/hmrc/tai/connectors/RtiConnector.scala
- app/uk/gov/hmrc/tai/model/domain/EmploymentBuilder.scala
- app/uk/gov/hmrc/tai/model/domain/IabdDetails.scala
- app/uk/gov/hmrc/tai/model/domain/RealTimeStatus.scala
- build.sbt
- it/test/uk/gov/hmrc/tai/integration/TaxAccountSummaryHipToggleTaxAccountOnSpec.scala
- test/uk/gov/hmrc/tai/connectors/RtiConnectorSpec.scala
- test/uk/gov/hmrc/tai/model/domain/EmploymentBuilderSpec.scala
- test/uk/gov/hmrc/tai/model/domain/EmploymentSpec.scala
- test/uk/gov/hmrc/tai/model/domain/RealTimeStatusSpec.scala
- test/uk/gov/hmrc/tai/service/IabdServiceSpec.scala
> Ddcnl 9489

- app/uk/gov/hmrc/tai/model/domain/IabdDetails.scala
- test/uk/gov/hmrc/tai/service/IabdServiceSpec.scala
> fixed compiling issues

- app/uk/gov/hmrc/tai/config/ApplicationStartUp.scala
- app/uk/gov/hmrc/tai/connectors/IabdConnector.scala
- app/uk/gov/hmrc/tai/model/IabdUpdateAmount.scala
- app/uk/gov/hmrc/tai/model/admin/FeatureFlags.scala
- it/test/uk/gov/hmrc/tai/integration/UpdateIncomeHipToggleTaxAccountAndIabdEmploymentOnSpec.scala
- it/test/uk/gov/hmrc/tai/integration/UpdateIncomeHipToggleTaxAccountOnSpec.scala
- it/test/uk/gov/hmrc/tai/integration/utils/IntegrationSpec.scala
- test/uk/gov/hmrc/tai/connectors/IabdConnectorSpec.scala
> Ddcnl 9477

- app/uk/gov/hmrc/tai/model/domain/NpsIabdSummaryHipReads.scala
- app/uk/gov/hmrc/tai/model/domain/income/TaxCodeIncomeHipReads.scala
- test/resources/data/TaxAccount/CodingComponent/hip/tc33.json
- test/resources/data/TaxAccount/CodingComponent/hip/tc34.json
- test/resources/data/TaxAccount/TaxCodeIncome/hip/TC01.json
- test/resources/data/TaxAccount/TaxCodeIncome/hip/TC02.json
- test/resources/data/TaxAccount/TaxCodeIncome/hip/TC05.json
- test/resources/data/TaxAccount/TaxCodeIncome/hip/TC06.json
- test/resources/data/TaxAccount/TaxCodeIncome/hip/TC07.json
- test/resources/data/TaxAccount/TaxCodeIncome/hip/TC08.json
- test/resources/data/TaxAccount/TaxCodeIncome/hip/TC09.json
- test/resources/data/TaxAccount/TaxCodeIncome/hip/TC10.json
- test/resources/data/TaxAccount/TaxCodeIncome/hip/TC11.json
- test/resources/data/TaxAccount/TaxCodeIncome/hip/TC23.json
- test/uk/gov/hmrc/tai/model/domain/calculation/CodingComponentHipReadsSpec.scala
- test/uk/gov/hmrc/tai/model/domain/income/TaxCodeIncomeHipReadsSpec.scala
- test/uk/gov/hmrc/tai/service/helper/TaxAccountHelperHipToggleOnSpec.scala
> Ddcnl 9634

- app/uk/gov/hmrc/tai/connectors/IabdConnector.scala
- it/test/uk/gov/hmrc/tai/integration/UpdateIncomeHipToggleTaxAccountAndIabdEmploymentOnSpec.scala
- test/uk/gov/hmrc/tai/connectors/IabdConnectorSpec.scala
> Ddcnl 9648

- app/uk/gov/hmrc/tai/connectors/HttpHandler.scala
- app/uk/gov/hmrc/tai/connectors/IabdConnector.scala
- test/uk/gov/hmrc/tai/connectors/HttpHandlerSpec.scala
> Ddcnl 9633

- app/uk/gov/hmrc/tai/connectors/HttpHandler.scala
- it/test/uk/gov/hmrc/tai/integration/UpdateIncomeHipToggleTaxAccountAndIabdEmploymentOnSpec.scala
- test/uk/gov/hmrc/tai/connectors/IabdConnectorSpec.scala
> fixed double encoding of url

- app/uk/gov/hmrc/tai/model/domain/NpsIabdSummaryHipReads.scala
- app/uk/gov/hmrc/tai/util/SequenceHelper.scala
- it/test/uk/gov/hmrc/tai/integration/resources/taxAccountHip.json
- test/resources/data/TaxAccount/CodingComponent/hip/tc35.json
- test/uk/gov/hmrc/tai/model/domain/NpsIabdSummaryHipReadsDuplicateCheckerSpec.scala
- test/uk/gov/hmrc/tai/model/domain/calculation/CodingComponentHipReadsSpec.scala
- test/uk/gov/hmrc/tai/util/SequenceHelperSpec.scala
> DDCNL-9643

- app/uk/gov/hmrc/tai/controllers/income/IncomeController.scala
> DDCNL-9729 Add logging for non matching ceased employments

- app/uk/gov/hmrc/tai/controllers/income/IncomeController.scala
> Revert "DDCNL-9729 Add logging for non matching ceased employments"

- app/uk/gov/hmrc/tai/service/IncomeService.scala
> DDCNL-9780: Add logging in preparation of a change

- app/uk/gov/hmrc/tai/service/IncomeService.scala
> Added comment

- build.sbt
> Ddcnl 10153

- app/uk/gov/hmrc/tai/model/domain/IabdDetails.scala
> Missing iabd type

- app/uk/gov/hmrc/tai/connectors/IabdConnector.scala
- app/uk/gov/hmrc/tai/model/admin/FeatureFlags.scala
- app/uk/gov/hmrc/tai/model/domain/IabdDetails.scala
- build.sbt
- it/test/uk/gov/hmrc/tai/integration/PutEmployeeExpensesSpec.scala
- test/uk/gov/hmrc/tai/connectors/IabdConnectorSpec.scala
- test/uk/gov/hmrc/tai/model/domain/IabdDetailsSpec.scala
> Ddcnl 10202

- app/uk/gov/hmrc/tai/config/CustomErrorHandler.scala
> refactor exceptions logging

- app/uk/gov/hmrc/tai/service/IncomeService.scala
- app/uk/gov/hmrc/tai/service/helper/TaxCodeIncomeHelper.scala
- test/uk/gov/hmrc/tai/service/IncomeServiceSpec.scala
- test/uk/gov/hmrc/tai/service/helper/TaxCodeIncomeHelperSpec.scala
> Ddcnl 10085: made tax account optional when updating income

- app/uk/gov/hmrc/tai/config/ApplicationStartUp.scala
- app/uk/gov/hmrc/tai/connectors/IabdConnector.scala
- app/uk/gov/hmrc/tai/connectors/TaxAccountConnector.scala
- app/uk/gov/hmrc/tai/model/admin/FeatureFlags.scala
- it/test/uk/gov/hmrc/tai/integration/PutEmployeeExpensesSpec.scala
- it/test/uk/gov/hmrc/tai/integration/utils/IntegrationSpec.scala
- project/plugins.sbt
- test/uk/gov/hmrc/tai/connectors/ConnectorBaseSpec.scala
- test/uk/gov/hmrc/tai/connectors/IabdConnectorSpec.scala
- test/uk/gov/hmrc/tai/connectors/TaxAccountConnectorSpec.scala
> DDCNL-10607

- app/uk/gov/hmrc/tai/connectors/IabdConnector.scala
- app/uk/gov/hmrc/tai/model/admin/FeatureFlags.scala
- app/uk/gov/hmrc/tai/model/domain/IabdDetails.scala
- app/uk/gov/hmrc/tai/model/nps/NpsIabdRoot.scala
- app/uk/gov/hmrc/tai/service/IabdService.scala
- app/uk/gov/hmrc/tai/service/expenses/EmployeeExpensesService.scala
- app/uk/gov/hmrc/tai/util/JsonHelper.scala
- it/test/uk/gov/hmrc/tai/integration/GetEmployeeExpensesSpec.scala
- it/test/uk/gov/hmrc/tai/integration/resources/hipiabdsType59.json
- test/uk/gov/hmrc/tai/connectors/IabdConnectorSpec.scala
- test/uk/gov/hmrc/tai/service/IabdServiceSpec.scala
- test/uk/gov/hmrc/tai/service/expenses/EmployeeExpensesServiceSpec.scala
> DDCNL-10783: move get iabd for employee expenses to hip behind a toggle

- app/uk/gov/hmrc/tai/config/ApplicationStartUp.scala
- app/uk/gov/hmrc/tai/controllers/EmploymentsController.scala
> Added new toggle to startup list

- app/uk/gov/hmrc/tai/config/CustomErrorHandler.scala
- app/uk/gov/hmrc/tai/connectors/HipHeaders.scala
- app/uk/gov/hmrc/tai/connectors/IabdConnector.scala
- app/uk/gov/hmrc/tai/connectors/TaxAccountConnector.scala
- project/AppDependencies.scala
- project/plugins.sbt
- test/uk/gov/hmrc/tai/connectors/IabdConnectorSpec.scala
> DDCNL-10804: correct headers for update iabd hip

- app/uk/gov/hmrc/tai/model/nps/NpsIabdRoot.scala
- test/uk/gov/hmrc/tai/service/expenses/EmployeeExpensesServiceSpec.scala
> Allow empty response from iabds hip
